name: main
on:
  push:
    branches: ['main']

permissions:
  id-token: write
  contents: read

jobs:
  check-versions:
    name: Check Versions
    environment: production
    runs-on: ubuntu-latest
    outputs:
      publishedVersion: ${{ steps.versions.outputs.publishedVersion }}
      pushedVersion: ${{ steps.versions.outputs.pushedVersion }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
        name: Setup Node.js
      - id: versions
        name: Query versions
        run: |
          PUSHED_VERSION=$(cat package-lock.json | jq -r '.version')

          if [[ "$PUSHED_VERSION" == *"beta"* ]]; then
            PUBLISHED_VERSION=$(npm view @wabot-dev/framework dist-tags.beta)
          else
            PUBLISHED_VERSION=$(npm view @wabot-dev/framework version)
          fi

          echo "PUBLISHED_VERSION=$PUBLISHED_VERSION"
          echo "PUSHED_VERSION=$PUSHED_VERSION"

          echo "publishedVersion=$PUBLISHED_VERSION" >> "$GITHUB_OUTPUT"
          echo "pushedVersion=$PUSHED_VERSION" >> "$GITHUB_OUTPUT"

  publish-lib:
    name: Publish Lib
    environment: production
    needs: check-versions
    runs-on: ubuntu-latest
    if: ${{ needs.check-versions.outputs.publishedVersion != needs.check-versions.outputs.pushedVersion }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
        name: Setup Node.js

      - name: Run publish
        run: |
          VERSION_TO_PUBLISH=${{ needs.check-versions.outputs.pushedVersion }}

          npm ci
          npm run build

          if [[ "$VERSION_TO_PUBLISH" == *"beta"* ]]; then
            npm publish --access=public --tag beta --provenance
          else
            npm publish --access=public --provenance
          fi
